services:
  - type: web
    name: go-runner-wasm
    env: docker
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: ""
    ports:
      - 8080
    region: oregon
    plan: free
    autoDeploy: true